# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Pre-Dependencies
          command: mkdir -p ~/repo/artifacts

      - restore_cache:
          key: repo-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm i --silent

      - run:
          name: Install Extra Dependencies
          command: npm i codecov --silent

      - save_cache:
          paths:
            - node_modules
          key: repo-{{ checksum "package.json" }}

      - run:
          name: Run Linting
          command: npm run lint -s

      - run:
          name: Run Type checking
          command: npm run types -s

      - run:
          name: Run Unit Tests
          command: npm run test -- --coverage

      - run:
          name: Upload coverage results
          command: ./node_modules/.bin/codecov

      - store_test_results:
          path: ~/repo/coverage

      - store_artifacts:
          path: ~/repo/artifacts
          destination: artifacts
